In [3]:
import numpy as np
A = np.array([[25,0,1],[20,1,2],[40,1,6]])
b = np.array([[110],[110],[210]])

# To see rank, use: 
np.linalg.matrix_rank(A)

# To invert a matrix, use:
np.linalg.inv(A)

# To multiply matrices in Python 3, use:
# A@B
print(np.linalg.inv(A.transpose()@A)@A.transpose()@b)

[[ 4.25]
 [17.5 ]
 [ 3.75]]


In [6]:
import numpy as np
A = np.array([[25,15,10,0,1],[20,12,8,1,2],[40,30,10,1,6], [30,15,15,0,3], [35,20,15,2,4]])
b = np.array([[104],[97],[193],[132],[174]])

print(np.linalg.matrix_rank(A))

# Note: you can use np.hstack() to concatinate vectors, for example np.hstack((A,b))

# Note: you can select all the columns, except the first of a matrix A as:  A[:,1:]
print(np.linalg.inv(A[:,1:].transpose()@A[:,1:])@A[:,1:].transpose()@b)

4
[[4.]
 [4.]
 [9.]
 [4.]]


In [9]:
A = np.array([[.5,.5],[.5,-.5],[.5,-.5],[.5,.5]])
b = np.array([[1,1,1],[1,-2,1]])
print(np.linalg.matrix_rank(A@b))
print(A@b)

2
[[ 1.  -0.5  1. ]
 [ 0.   1.5  0. ]
 [ 0.   1.5  0. ]
 [ 1.  -0.5  1. ]]


In [10]:
print(A.transpose()@A)

[[1. 0.]
 [0. 1.]]
