In [121]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt 

in_data = loadmat('movie.mat')
#loadmat() loads a matlab workspace into a python dictionary, where the names of the variables are the keys 
#in the dictionary.  To see what variables are loaded, uncomment the line below: 
print([key for key in in_data])

M = in_data['M']
print(M)

['__header__', '__version__', '__globals__', 'M', 'ans']
[[ 4  7  2  8  7  4  2]
 [ 9  3  5  6 10  5  5]
 [ 4  8  3  7  6  4  1]
 [ 9  2  6  5  9  5  4]
 [ 4  9  2  8  7  4  1]]


In [130]:
# get sum of each column
col_sum = np.sum(M, axis=0)
N = []
for i in col_sum:
  # divide by sqrt of 5
  N.append(np.round(i/np.sqrt(5)/5, 2))
print(N)

[2.68, 2.59, 1.61, 3.04, 3.49, 1.97, 1.16]


In [131]:
L = np.zeros((5,7))
# subtract N[i] from each column with
for i in range(5):
  for j in range(7):
    L[i][j] = np.round(M[i][j] - N[j], 2)
print(L)

[[ 1.32  4.41  0.39  4.96  3.51  2.03  0.84]
 [ 6.32  0.41  3.39  2.96  6.51  3.03  3.84]
 [ 1.32  5.41  1.39  3.96  2.51  2.03 -0.16]
 [ 6.32 -0.59  4.39  1.96  5.51  3.03  2.84]
 [ 1.32  6.41  0.39  4.96  3.51  2.03 -0.16]]
